source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'EVTTabPageScrollView_Example', :exclusive => true do
  pod "EVTTabPageScrollView", :path => "../"
end

target 'EVTTabPageScrollView_Tests', :exclusive => true do
  pod "EVTTabPageScrollView", :path => "../"

  
end
