source 'https://github.com/CocoaPods/Specs.git'

target 'EVTTabPageScrollView_Example', :exclusive => true do
    pod 'Masonry', '~> 0.6'
  pod "EVTTabPageScrollView", :path => "../"
end

target 'EVTTabPageScrollView_Tests', :exclusive => true do
  pod "EVTTabPageScrollView", :path => "../"

  
end
