# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'bukuzao' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for bukuzao
#pod 'EasyReact'

  target 'bukuzaoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'bukuzaoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
